// Code generated by mockery 2.9.0. DO NOT EDIT.

package dependency

import mock "github.com/stretchr/testify/mock"

// MockOption is an autogenerated mock type for the Option type
type MockOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockOption) Execute(_a0 *deps) {
	_m.Called(_a0)
}
