// Code generated by mockery 2.9.0. DO NOT EDIT.

package usecase

import (
	context "context"
	domain "webarticles/internal/modules/article/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleUsecase is an autogenerated mock type for the ArticleUsecase type
type MockArticleUsecase struct {
	mock.Mock
}

// CreateArticle provides a mock function with given fields: ctx, article
func (_m *MockArticleUsecase) CreateArticle(ctx context.Context, article *domain.Article) (*domain.Article, error) {
	ret := _m.Called(ctx, article)

	var r0 *domain.Article
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Article) *domain.Article); ok {
		r0 = rf(ctx, article)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Article) error); ok {
		r1 = rf(ctx, article)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, filter
func (_m *MockArticleUsecase) FindAll(ctx context.Context, filter *domain.Filter) ([]*domain.Article, error) {
	ret := _m.Called(ctx, filter)

	var r0 []*domain.Article
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Filter) []*domain.Article); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Filter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, ID
func (_m *MockArticleUsecase) FindByID(ctx context.Context, ID *string) (*domain.Article, error) {
	ret := _m.Called(ctx, ID)

	var r0 *domain.Article
	if rf, ok := ret.Get(0).(func(context.Context, *string) *domain.Article); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Article)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
