// Code generated by mockery 2.9.0. DO NOT EDIT.

package factory

import (
	interfaces "webarticles/pkg/codebase/interfaces"

	mock "github.com/stretchr/testify/mock"

	types "webarticles/pkg/codebase/factory/types"
)

// MockModuleFactory is an autogenerated mock type for the ModuleFactory type
type MockModuleFactory struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *MockModuleFactory) Name() types.Module {
	ret := _m.Called()

	var r0 types.Module
	if rf, ok := ret.Get(0).(func() types.Module); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(types.Module)
	}

	return r0
}

// RestHandler provides a mock function with given fields:
func (_m *MockModuleFactory) RestHandler() interfaces.EchoRestHandler {
	ret := _m.Called()

	var r0 interfaces.EchoRestHandler
	if rf, ok := ret.Get(0).(func() interfaces.EchoRestHandler); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.EchoRestHandler)
		}
	}

	return r0
}
