// Code generated by mockery 2.9.0. DO NOT EDIT.

package factory

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAppServerFactory is an autogenerated mock type for the AppServerFactory type
type MockAppServerFactory struct {
	mock.Mock
}

// Serve provides a mock function with given fields:
func (_m *MockAppServerFactory) Serve() {
	_m.Called()
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockAppServerFactory) Shutdown(ctx context.Context) {
	_m.Called(ctx)
}
