// Code generated by mockery 2.9.0. DO NOT EDIT.

package interfaces

import mock "github.com/stretchr/testify/mock"

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

// ValidateDocument provides a mock function with given fields: reference, document
func (_m *MockValidator) ValidateDocument(reference string, document []byte) error {
	ret := _m.Called(reference, document)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(reference, document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateStruct provides a mock function with given fields: data
func (_m *MockValidator) ValidateStruct(data interface{}) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
