// Code generated by mockery 2.9.0. DO NOT EDIT.

package interfaces

import (
	echo "github.com/labstack/echo"
	mock "github.com/stretchr/testify/mock"
)

// MockEchoRestHandler is an autogenerated mock type for the EchoRestHandler type
type MockEchoRestHandler struct {
	mock.Mock
}

// Mount provides a mock function with given fields: group
func (_m *MockEchoRestHandler) Mount(group *echo.Group) {
	_m.Called(group)
}
