// Code generated by mockery 2.9.0. DO NOT EDIT.

package interfaces

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
)

// MockSQLDatabase is an autogenerated mock type for the SQLDatabase type
type MockSQLDatabase struct {
	mock.Mock
}

// Disconnect provides a mock function with given fields: ctx
func (_m *MockSQLDatabase) Disconnect(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSQLDB provides a mock function with given fields:
func (_m *MockSQLDatabase) GetSQLDB() *sql.DB {
	ret := _m.Called()

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}
